### ISSUE TITLE
Decimal values are mentioned with `,` instead of `.`

### ISSUE THREAD

**Issue by utkarsh1311** [vladocar/flexy#3]
Decimal values are written with `,` instead of `.` at many places in the `README.md` as well as in the website itself.
I am not sure if this was on purpose but I think it should be corrected to avoid confusion.

**Comment by yung-coder** [comment]
I would like to work on this @utkarsh1311

**Comment by SachinCoder1** [comment]
Assign it to me.

**Comment by mihir2226** [comment]
Hi @utkarsh1311, I updated the README.md file, give me the write access.
